### ISSUE TITLE
Missing Xeon processors

### ISSUE THREAD

**Issue by przemowcf** [toUpperCase78/intel-processors#1]
Hello,

Thanks for dataset! I wanted to have list of xeon cpu that are supported by win11 so I made cross reference with MS list and yours, and found that you're missing some Xoen CPUs: 
- ```Xeon E-2104G``` [IntelARK:Xeon E-2104G](https://ark.intel.com/content/www/us/en/ark/products/134929/intel-xeon-e2104g-processor-8m-cache-3-20-ghz.html)
- ```Silver 4108``` [IntelARK:Silver 4108](https://ark.intel.com/content/www/us/en/ark/products/123544/intel-xeon-silver-4108-processor-11m-cache-1-80-ghz.html)
- ```W-2102``` [IntelARK:W-2102](https://ark.intel.com/content/www/us/en/ark/products/125038/intel-xeon-w2102-processor-8-25m-cache-2-90-ghz.html)
- ```W-2104``` [IntelARK:W-2104](https://ark.intel.com/content/www/us/en/ark/products/125039/intel-xeon-w2104-processor-8-25m-cache-3-20-ghz.html)

Also MS have on it's list few Gold&Platinum ```M``` versions that ark.intel.com can't find (*No products matching your request were found.*), but those can be found with google (on some shops, amazon, ebay, etc...), also there is one with ```CL``` 🤨 

If anyone is interested, I can share this sheet.

**Comment by toUpperCase78** [comment]
Hello there,

First of all, thank you for your interest of these datasets! Keep in mind that I'm updating these processor datasets generally on annual basis and form them as they are "exactly" found on the related lists in Intel Product Specs web site. Thus they might be a bit outdated after some time and I don't check if there are other unlisted processors afterwards.

From your comment, I suppose "MS list" should mean the Xeon processor list that supports Windows 11, given by Microsoft. It's a bit strange to see that several processors didn't make into the lists in Intel's site, although you claim that they have their own spec pages and are found on other web sites.

Moreover, let me go over the processors you mentioned above for clarification:

- **Xeon E-2104G:** It has its own spec page but was not added to the Xeon E processor list.
- **Silver 4108:** This can be found on the corresponding list, but realized that I made a typo by writing as "Silver 4018" in my dataset. This is going to be corrected.
- **W-2102 & W-2104:** Similar to E-2104G, their spec pages are available, but not found under their list.
